_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 13
                - 19
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.6
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: cu_us2
encoder:
    value: vision
logit_scale:
    value: 100
lr:
    value: 0.0003
model_name:
    value: vit_google
n_iters:
    value: 100
params:
    value:
        - q
        - v
position:
    value: all
rank:
    value: 8
seed:
    value: 2
shots:
    value: 16
weight_decay:
    value: 0.01
